<a href="https://colab.research.google.com/github/mahisewinet/Neural-network-practice/blob/main/Neural_network_practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
np.random.seed(0) # Set a random seed for reproducibility

X = [[1, 2, 3, 2.5], # Input data (a list of lists)
          [2, 5, -1, 2],
          [-1.5, 2.7, 3.3, -0.8]]

# Define a class for a dense layer in a neural network
class Layer_Dense:
  # Initialize the layer with the number of inputs and neurons
  def __init__(self, n_inputs, n_neurons):
    # Initialize weights with random values scaled by 0.10
    self.weights = 0.10*np.random.randn(n_inputs, n_neurons)
    # Initialize biases as zeros
    self.biases = np.zeros((1,n_neurons))

  # Perform the forward pass through the layer
  def forward(self, inputs):
    # Calculate the output using the dot product of inputs and weights, plus biases
    self.output = np.dot(inputs, self.weights) + self.biases

# Create an instance of the first dense layer with 4 inputs and 5 neurons
layer1= Layer_Dense(4, 5)
# Create an instance of the second dense layer with 5 inputs and 2 neurons
layer2= Layer_Dense(5, 2)

# Perform the forward pass for the first layer using the input data X
layer1.forward(X)
# Print the output of the first layer
print(layer1.output)
# Perform the forward pass for the second layer using the output of the first layer
layer2.forward(layer1.output)
# Print the output of the second layer
print(layer2.output)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]
