<a href="https://colab.research.google.com/github/mahisewinet/Neural-network-practice/blob/main/Softmax_activation_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
'''
import math

layer_outputs = [4.8, 1.21, 2.385]
E= math.e
exp_values= []

for output in layer_outputs:
    exp_values.append(E**output)

print(exp_values)

norm_base= sum(exp_values)
norm_values= []
for value in exp_values:
    norm_values.append(value/ norm_base)

print(norm_values)
print(sum(norm_values))

import math
import numpy as np

layer_outputs = [4.8, 1.21, 2.385]
E= math.e
exp_values= np.exp(layer_outputs)

print(exp_values)

norm_values= exp_values/ np.sum(exp_values)

print(norm_values)
print(sum(norm_values))
'''
import numpy as np

layer_outputs = [[4.8, 1.21, 2.385],
                 [8.9, -1.81, 0.2],
                 [1.41, 1.051, 0.026]]

exp_values= np.exp(layer_outputs)


norm_values= exp_values/ np.sum(exp_values, axis=1, keepdims=True)

print(norm_values)

[[1.21510418e+02 3.35348465e+00 1.08590627e+01]
 [7.33197354e+03 1.63654137e-01 1.22140276e+00]
 [4.09595540e+00 2.86051020e+00 1.02634095e+00]]
[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]
